[collectPlans.iosevka-codex-link]
from = ["iosevka-codex-link-normal", "iosevka-codex-link-term"]

[buildPlans.iosevka-codex-link-normal]
family = "Iosevka + CodexLink (Normal)"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-codex-link-normal.variants]
  inherits = "ss08"

    [buildPlans.iosevka-codex-link-normal.variants.design]
    pilcrow = "high"
    caret = "high"
    number-sign = "upright"
    at = "fourfold"
    dollar = "through"
    cent = "open"
    percent = "dots"
    bar = "force-upright"
    lig-ltgteq = "slanted"
    ascii-single-quote = "raised-comma"
    ascii-grave = "raised-inverse-comma"
    question = "corner"
    punctuation-dot = "square"
    diacritic-dot = "square"

  [buildPlans.iosevka-codex-link-normal.ligations]
  inherits = "dlig"

[buildPlans.iosevka-codex-link-normal.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-codex-link-normal.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-codex-link-normal.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-codex-link-normal.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-codex-link-normal.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-codex-link-normal.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-codex-link-term]
family = "Iosevka + CodexLink (Term)"
spacing = "term"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-codex-link-term.variants]
  inherits = "ss08"

    [buildPlans.iosevka-codex-link-term.variants.design]
    pilcrow = "high"
    caret = "high"
    number-sign = "upright"
    at = "fourfold"
    dollar = "through"
    cent = "open"
    percent = "dots"
    bar = "force-upright"
    lig-ltgteq = "slanted"
    ascii-single-quote = "raised-comma"
    ascii-grave = "raised-inverse-comma"
    question = "corner"
    punctuation-dot = "square"
    diacritic-dot = "square"

  [buildPlans.iosevka-codex-link-term.ligations]
  inherits = "dlig"

[buildPlans.iosevka-codex-link-term.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-codex-link-term.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-codex-link-term.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-codex-link-term.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-codex-link-term.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-codex-link-term.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

