[buildPlans.iosevka-codex-link-term-pref]
family = "Iosevka + CodexLink Term Pref"
spacing = "term"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-codex-link-term-pref.variants]
  inherits = "ss08"

  [buildPlans.iosevka-codex-link-term-pref.ligations]
  inherits = "dlig"

[buildPlans.iosevka-codex-link-term-pref.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-codex-link-term-pref.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-codex-link-term-pref.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-codex-link-term-pref.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-codex-link-term-pref.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-codex-link-term-pref.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-codex-link-term-pref.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-codex-link-term-pref.slopes.oblique]
angle = 9.4
shape = "oblique"
menu = "oblique"
css = "oblique"
