[buildPlans.IosevkaCodexLink]
family = "Iosevka + CodexLink"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaCodexLink.variants]
  inherits = "ss08"

    [buildPlans.IosevkaCodexLink.variants.design]
    diacritic-dot = "square"
    punctuation-dot = "square"
    underscore = "high"
    caret = "high"
    ascii-grave = "raised-inverse-comma"
    ascii-single-quote = "raised-comma"
    number-sign = "upright"
    at = "fourfold"
    dollar = "through"
    cent = "open"
    percent = "dots"
    bar = "force-upright"
    question = "corner"
    pilcrow = "high"
    lig-ltgteq = "slanted"

  [buildPlans.IosevkaCodexLink.ligations]
  inherits = "dlig"

[buildPlans.IosevkaCodexLink.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCodexLink.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCodexLink.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCodexLink.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaCodexLink.weights.Bold]
shape = 700
menu = 700
css = 700
