[buildPlans.iosevka-codex-link]
family = "Iosevka + CodexLink"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-codex-link.variants]
  inherits = "ss08"

    [buildPlans.iosevka-codex-link.variants.design]
    underscore = "high"
    pilcrow = "high"
    caret = "high"
    number-sign = "upright"
    at = "fourfold"
    dollar = "through"
    cent = "open"
    percent = "dots"
    bar = "force-upright"
    ascii-single-quote = "raised-comma"
    ascii-grave = "raised-inverse-comma"
    question = "corner"
    punctuation-dot = "square"
    diacritic-dot = "square"
    lig-ltgteq = "slanted"

  [buildPlans.iosevka-codex-link.ligations]
  inherits = "dlig"

[buildPlans.iosevka-codex-link.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-codex-link.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-codex-link.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-codex-link.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-codex-link.weights.bold]
shape = 700
menu = 700
css = 700
