---@module 'colorscheme'
---@author CodexLink <https://github.com/CodexLink>
---@license Apache-2.0
---@info [1] Higher priority is required for the colorscheme, as stated by the author of the package manager.

return {
  "rebelot/kanagawa.nvim",
  lazy = false,
  priority = 1000,
  config = function()
    require("kanagawa").setup({
      undercurl = true,
      commentStyle = { italic = true },
      functionStyle = { bold = true },
      keywordStyle = { italic = true },
      statementStyle = { bold = true },
      typeStyle = {},
      variablebuiltinStyle = { italic = true },
      specialReturn = true,
      specialException = true,
      transparent = false,
      dimInactive = true,
      globalStatus = true,
      terminalColors = true,
      theme = "dragon",
      overrides = function(colors)
        return {
          BufferLineBufferSelected = { bg = colors.palette.autumnYellow, bold = true, fg = colors.palette.sumiInk1 },
          BufferLineDevIconDefaultSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconGitCommitSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconGoSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconGitIgnoreSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconHtmlSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconJsSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconJsonSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconLicenseSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconLogSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconLuaSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconMarkdownSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconMdSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconPackageJsonSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconPySelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconPsScriptfileSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconPsScriptModulefileSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconTsSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconTsxSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDevIconYamlSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineDuplicateSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLineErrorVisible = { bold = true, fg = colors.palette.autumnRed, italic = false },
          BufferLineErrorSelected = { bg = colors.palette.autumnYellow, bold = true, fg = colors.palette.samuraiRed,
            italic = false },
          BufferLineHintVisible = { bold = true, fg = colors.palette.sprintViolet1, italic = false },
          BufferLineHintSelected = { bg = colors.palette.autumnYellow, bold = true, fg = colors.palette.oniViolet,
            italic = false },
          BufferLineInfoVisible = { bold = true, fg = colors.palette.lightBlue, italic = false },
          BufferLineInfoSelected = { bg = colors.palette.autumnYellow, bold = true, fg = colors.palette.springBlue,
            italic = false },
          BufferLineWarningVisible = { bold = true, fg = colors.palette.boatYellow2, italic = false },
          BufferLineWarningSelected = { bg = colors.palette.autumnYellow, bold = true, fg = colors.palette.boatYellow1,
            italic = false },
          BufferLineIndicatorSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.fujiWhite },
          BufferLineModifiedSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.sumiInk1 },
          BufferLinePickSelected = { bg = colors.palette.autumnYellow, fg = colors.palette.samuraiRed },
          CmpItemAbbrDeprecated = { bg = "NONE", fg = colors.palette.waveRed, strikethrough = true },
          CmpItemAbbrMatch = { bg = "NONE", bold = true, fg = colors.palette.waveRed },
          CmpItemAbbrMatchFuzzy = { bg = "NONE", bold = true, fg = colors.palette.waveRed },
          CmpItemMenu = { bg = "NONE", fg = colors.palette.carpYellow, bold = true },
          CmpItemKindField = { bg = colors.palette.sakuraPink, fg = colors.palette.sumiInk1 },
          CmpItemKindProperty = { bg = colors.palette.sakuraPink, fg = colors.palette.sumiInk1 },
          CmpItemKindEvent = { bg = colors.palette.sakuraPink, fg = colors.palette.sumiInk1 },
          CmpItemKindText = { bg = colors.palette.springGreen, fg = colors.palette.sumiInk1 },
          CmpItemKindEnum = { bg = colors.palette.springGreen, fg = colors.palette.sumiInk1 },
          CmpItemKindKeyword = { bg = colors.palette.springGreen, fg = colors.palette.sumiInk1 },
          CmpItemKindConstant = { bg = colors.palette.carpYellow, fg = colors.palette.sumiInk1 },
          CmpItemKindConstructor = { bg = colors.palette.carpYellow, fg = colors.palette.sumiInk1 },
          CmpItemKindReference = { bg = colors.palette.carpYellow, fg = colors.palette.sumiInk1 },
          CmpItemKindFunction = { bg = colors.palette.surimiOrange, fg = colors.palette.sumiInk1 },
          CmpItemKindStruct = { bg = colors.palette.surimiOrange, fg = colors.palette.sumiInk1 },
          CmpItemKindClass = { bg = colors.palette.surimiOrange, fg = colors.palette.sumiInk1 },
          CmpItemKindModule = { bg = colors.palette.surimiOrange, fg = colors.palette.sumiInk1 },
          CmpItemKindOperator = { bg = colors.palette.surimiOrange, fg = colors.palette.sumiInk1 },
          CmpItemKindVariable = { bg = colors.palette.waveRed, fg = colors.palette.sumiInk1 },
          CmpItemKindFile = { bg = colors.palette.waveRed, fg = colors.palette.sumiInk1 },
          CmpItemKindUnit = { bg = colors.palette.autumnRed, fg = colors.palette.sumiInk1 },
          CmpItemKindSnippet = { bg = colors.palette.autumnRed, fg = colors.palette.sumiInk1 },
          CmpItemKindFolder = { bg = colors.palette.autumnRed, fg = colors.palette.sumiInk1 },
          CmpItemKindMethod = { bg = colors.palette.roninYellow, fg = colors.palette.sumiInk1 },
          CmpItemKindValue = { bg = colors.palette.roninYellow, fg = colors.palette.sumiInk1 },
          CmpItemKindEnumMember = { bg = colors.palette.roninYellow, fg = colors.palette.sumiInk1 },
          CmpItemKindInterface = { bg = colors.palette.fujiWhite, fg = colors.palette.sumiInk1 },
          CmpItemKindColor = { bg = colors.palette.fujiWhite, fg = colors.palette.sumiInk1 },
          CmpItemKindTypeParameter = { bg = colors.palette.fujiWhite, fg = colors.palette.sumiInk1 },
          CursorToNavigation = { fg = "NONE", bg = colors.palette.roninYellow },
          CursorToInsertion = { fg = "NONE", bg = colors.palette.surimiOrange },
          CursorToReplacement = { fg = colors.palette.autumnYellow, bg = colors.palette.samuraiRed },
          -- NOTE: This highlight may work based on your terminal, currently this does not work in my case.
          Cursor = { bg = colors.palette.surimiOrange, fg = colors.palette.surimiOrange },
          TermCursor = { bg = colors.palette.surimiOrange, fg = colors.palette.surimiOrange },
          HighlightedYank = { bg = colors.palette.roninYellow, fg = colors.palette.sumiInk1 },
          IlluminatedWordRead = { bg = colors.palette.carpYellow, bold = true, fg = colors.palette.sumiInk1 },
          IlluminatedWordText = { bg = colors.palette.oldWhite, fg = colors.palette.sumiInk1, underline = false },
          IlluminatedWordWrite = { bg = colors.palette.sakuraPink, bold = true, fg = colors.palette.sumiInk1 },
          Visual = { bg = colors.palette.waveRed, fg = colors.palette.sumiInk1 },
          Pmenu = { bg = colors.palette.sumiInk2, fg = colors.palette.sakuraPink },
          PmenuSel = { bg = colors.palette.carpYellow, fg = colors.palette.sumiInk1 },
        }
      end
    })

    require("kanagawa").load()
  end
}
