name: Font Builder + Patch to Repository Release

on:
  workflow_dispatch:

jobs:
  font-build:
    name: Font Builder | Iosevka
    runs-on: ubuntu-latest

    steps:
      - name: Step 0 | Main Repository Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            font/private-build-plans.toml

      - name: Step 1 | Font (Iosevka) Repository Checkout
        uses: actions/checkout@v4
        with:
          repository: be5invis/Iosevka
          path: font-repo
          fetch-depth: 1

      - name: Step 2 | Setup Node.js
        uses: actions/setup-node@v4

      - name: Step 3 | Build Font
        working-directory: font-repo
        run: |
          npm install
          npm run build -- ttf::iosevka-codex-link

      - name: Debug | Assert
        run: |
          ls

  font-patcher:
    name: Font Patcher | Nerd Fonts
    runs-on: ubuntu-latest
    needs: font-build

    steps:
      - name: Step 0 | Font Patcher Repository Checkout
        uses: actions/checkout@v4
        with:
          repository: be5invis/Iosevka
          path: font-patcher
          sparse-checkout: |
            bin
            src/glyphs
            font-patcher

      - name: Debug | Assert
        run: |
          ls

      - name: Step - | Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          # run:
